### ISSUE TITLE
大佬您好,  规则出问题了?

### ISSUE THREAD

**Issue by razilong** [lingeringsound/adblock#1]

**Comment by lingeringsound** [comment]
好的，感谢反馈，我刚刚试了一下，Windows上面116内核的Edge正常工作，可拓这边也是正常的😂，加载速度基本没差。你可以选择 [混合规则自动更新](https://lingeringsound.github.io/adblock_auto) 看看，虽然我感觉还是可能会出问题😱，我再看看吧，不知道加了什么奇怪的规则(byd我原来合并的规则也就那几个🤔)。

**Comment by lingeringsound** [comment]
你现在更新试试？我删减了一些规则。

**Comment by lingeringsound** [comment]
好的，不不客气！也感谢你的反馈和测试😋！至于什么原因我也不太清楚，应该是某个css规则出了问题😂(删了最近加的一部分，定位比较模糊，不太确定是那个规则)。

**Comment by lingeringsound** [comment]
目前应该是没有这个打算😂，因为我自己不怎么用clash
